name: Build
on: push
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Install vsce
        run: |
          npm i vsce
      - name: Package
        run: |
          ./node_modules/vsce/out/vsce package